version: '3.8'

services:
  # Serviço do Banco de Dados PostgreSQL
  postgres:
    image: postgres:17.5
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres       # Usuário do banco
      POSTGRES_PASSWORD: 260698     # Senha do banco
      POSTGRES_DB: taskdb           # Nome do banco que será criado automaticamente
    ports:
      - "5432:5432"                 # Porta local:porta no container
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - local-network

  # Interface web para o banco (pgAdmin)
  pgadmin:
    image: dpage/pgadmin4:9.5
    container_name: pgadmin_ui
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: task-api.com   # Login pgAdmin
      PGADMIN_DEFAULT_PASSWORD: 260698        # Senha pgAdmin
    ports:
      - "8083:80"                    # Acesso via http://localhost:8083
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - local-network

volumes:
  postgres-data:
  pgadmin-data:

networks:
  local-network:
    driver: bridge
